# Generated by Django 2.2.2 on 2019-07-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('blog', '0003_auto_20190703_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ManyToManyField(related_name='posts', to='user.Profile'),
        ),
    ]
